### PR TITLE
Fix border rendering

### LINKED ISSUE #23: check borders of blocks are right
spotted that Quadrant has some dodgy corners:

Image

### PR DESCRIPTION
**Pull request by melix**
Fixes #23

### CODE REVIEW

File: tamboui-widgets/src/test/java/dev/tamboui/widgets/block/BlockTest.java [hunk 1]
```diff
@@ -163,6 +163,90 @@ void titleInheritsBorderStyle() {
...
+        Block block = Block.builder()
+            .borders(Borders.ALL)
+            .borderType(BorderType.QUADRANT_INSIDE)
+            .build();
+        Buffer buffer = Buffer.empty(area);
+
+        block.render(area, buffer);
+
+        // Corners
+        assertThat(buffer.get(0, 0).symbol()).isEqualTo("▖");  // top-left
```
Comment (maxandersen) [inline tamboui-widgets/src/test/java/dev/tamboui/widgets/block/BlockTest.java]: here using assertThat(buffer).isEqualTo(expected) would be nice ;)

Comment (melix) [reply tamboui-widgets/src/test/java/dev/tamboui/widgets/block/BlockTest.java]: Fixed ;)

**Comment by maxandersen** [comment]
running this give same weird corners - the characters in the test are wrong hence why it passes. working on fix.

**Comment by maxandersen** [comment]
with my latest push I get:

image

which matches what ratatui blocks demo has if enables quardrant inside style.

**Comment by melix** [comment]
Thanks!
