### PR TITLE
fix: Implement Fraction type

### LINKED ISSUE #91: consider use of Fraction type instead of double in layouts/pixel precision?
as lesson from https://www.textualize.io/blog/7-things-ive-learned-building-a-modern-tui-framework/ use of Fraction type (which can be quite simple on longs and/or BigInteger) can avoid one-off cell errors when we start adding/multiplying with doubles.

Mainly in layout engine - but might also be relevant other places.

Additional win is one can retain a more logical relevant representation "1/3" instead "0.333333333%"

### PR DESCRIPTION
**Pull request by melix**
This avoids cumulative rounding errors in the solver.

Fixes #91

### CODE REVIEW

File: tamboui-core/src/main/java/dev/tamboui/layout/Fraction.java [hunk 1]
```diff
@@ -0,0 +1,436 @@
...
+    /** The fraction representing zero (0/1). */
+    public static final Fraction ZERO = new Fraction(0, 1);
+
+    /** The fraction representing one (1/1). */
+    public static final Fraction ONE = new Fraction(1, 1);
+
+    /** The fraction representing negative one (-1/1). */
+    public static final Fraction NEG_ONE = new Fraction(-1, 1);
+
+    private final long numerator;
```
Comment (maxandersen) [inline tamboui-core/src/main/java/dev/tamboui/layout/Fraction.java:35]: just realizing we have Constraint.Ratio that has the same setup - should those two merge?

Also - kinda feels this Fraction is usable outside cassowary so maybe move to .layout directly ?

File: tamboui-core/src/main/java/dev/tamboui/layout/cassowary/LayoutSolver.java [hunk 2]
```diff
@@ -244,31 +249,57 @@ private void addEqualSizeTendency(Variable[] sizes) {
...
      *
-     * @param floatSizes the float sizes from the solver
-     * @param target     the maximum sum (available space)
+     * @param fractionSizes the exact Fraction sizes from the solver
+     * @param target        the maximum sum (available space)
      * @return integer sizes that sum to at most target
      */
-    private int[] roundWithConstraint(double[] floatSizes, int target) {
-        int n = floatSizes.length;
+    private int[] roundWithConstraint(Fraction[] fractionSizes, int target) {
```
Comment (maxandersen) [inline tamboui-core/src/main/java/dev/tamboui/layout/cassowary/LayoutSolver.java:265]: hmm - I wouldn't have expected this method to become more complex.

File: tamboui-core/src/main/java/dev/tamboui/layout/Constraint.java [hunk 3]
```diff
@@ -131,6 +131,15 @@ public int denominator() {
             return denominator;
         }
 
+        /**
+         * Converts this ratio to a Fraction for exact arithmetic.
+         *
+         * @return a Fraction representing this ratio
+         */
+        public Fraction toFraction() {
```
Comment (maxandersen) [inline tamboui-core/src/main/java/dev/tamboui/layout/Constraint.java:139]: any reason to keep ratio as a type? can't just it directly in the ratio methods?

Comment (melix) [reply tamboui-core/src/main/java/dev/tamboui/layout/Constraint.java:139]: Yes, one represents a `Constraint` (data class), the other one is a utility for computing.

Comment (maxandersen) [reply tamboui-core/src/main/java/dev/tamboui/layout/Constraint.java:139]: ok :)
